name: Accelerate doc build

# on: [pull_request]

jobs:
  integration_doc_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/checkout@v4
        with:
          repository: 'huggingface/doc-builder'
          path: doc-builder
      
      - uses: actions/checkout@v4
        with:
          repository: 'huggingface/accelerate'
          path: accelerate
          ref: 16eb6d76bf987c7d8d877ce5152f2e29878eab37

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Loading cache
        uses: actions/cache@v4
        id: cache
        with:
          path: ~/.cache/pip
          key: v1-test_build_doc
          restore-keys: |
            v1-test_build_doc-${{ hashFiles('setup.py') }}
            v1-test_build_doc

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Setup environment
        run: |
          cd doc-builder
          pip install .
          cd ..

          cd accelerate
          pip install .[dev]
          cd ..
          
      - name: Make documentation
        run: |
          cd doc-builder &&
          doc-builder build accelerate ../accelerate/docs/source --build_dir ../build_dir --clean --html &&
          cd ..
        env:
          NODE_OPTIONS: --max-old-space-size=6656
