
name: Accelerate doc build

on: [pull_request]

jobs:
  integration_doc_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/checkout@v4
        with:
          repository: 'huggingface/doc-builder'
          path: doc-builder
      
      - uses: actions/checkout@v4
        with:
          repository: 'huggingface/accelerate'
          path: accelerate
          ref: 16eb6d76bf987c7d8d877ce5152f2e29878eab37

      - name: Install uv
        uses: astral-sh/setup-uv@v7.2.0
        with:
          version: 'latest'

      - name: Ensure Python 3.10
        run: uv python install 3.10

      - name: Create virtual environment
        run: uv venv --python 3.10 .venv

      - name: Install Python dependencies
        run: uv pip install --python .venv/bin/python ./doc-builder './accelerate[dev]'

      - name: Make documentation
        run: |
          cd doc-builder &&
          ../.venv/bin/doc-builder build accelerate ../accelerate/docs/source --build_dir ../build_dir --clean --html &&
          cd ..
        env:
          NODE_OPTIONS: --max-old-space-size=6656